#!/usr/bin/env bash
# Installs nginx web server on a new ubuntu server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
