#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

i=0
while [ $i -eq 10 ]
do
    echo "Best School"
        if [i == 8]
            echo "Hi"
    ((i++))
done
