#!/usr/bin/env bash
# script that displays: The content of the current directory, in a list format, where only the part of the name after the first dash is displayed (refer to the example)

list=$(ls)
for file in $list; do
  echo "$file" | cut -d '-' -f2
done
